#!/bin/sh

VERSION=0.9.4

python setup.py sdist
cp dist/OSG_Display_Data-$VERSION.tar.gz `rpm -E '%{_sourcedir}'`
rpmbuild -ba config/OSG_Display_Data.spec
cp `rpm -E '%{_rpmdir}'`/noarch/OSG_Display_Data-$VERSION-1.noarch.rpm dist/

