#!/bin/sh

VERSION=1.0.1
RELEASE=1

python setup.py sdist
cp dist/OSG_Display_Data-$VERSION.tar.gz `rpm -E '%{_sourcedir}'`
rpmbuild -ba config/OSG_Display_Data.spec
cp `rpm -E '%{_rpmdir}'`/noarch/OSG_Display_Data-$VERSION-$RELEASE.noarch.rpm dist/

